config/routes.rb
Rails.application.routes.draw do
  resources :links
  devise_for :users
  resources :trees
  get "home/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"

  get "trees/add_link", to: "trees#add_link", as: "add_link"

  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :tree
end

app/models/tree.rb
class Tree < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :user
  has_many :link, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_one :tree, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Redirect the user to their tree. Redirect to new_tree if no tree has been created
  def after_sign_in_path_for(resource)
    if current_user&.tree
      tree_path(current_user.tree)
    else
      new_tree_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: %i[ show edit update destroy ]

  # GET /links or /links.json
  def index
    @links = Link.all
  end

  # GET /links/1 or /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links or /links.json
  def create
    # Only create link for the tree of the current user
    @tree = current_user.tree
    @link = @tree.link.build(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: "Link was successfully created." }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1 or /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: "Link was successfully updated." }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1 or /links/1.json
  def destroy
    @link.destroy!

    respond_to do |format|
      format.html { redirect_to links_path, status: :see_other, notice: "Link was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def link_params
      params.expect(link: [ :website_title, :logo_url, :website_url ])
    end
end

app/controllers/trees_controller.rb
class TreesController < ApplicationController
  before_action :set_tree, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ new edit update destroy ]

  # GET /trees or /trees.json
  def index
    @trees = Tree.all
  end

  # GET /trees/1 or /trees/1.json
  def show
  end

  # GET /trees/new
  def new
    @tree = Tree.new
  end

  # GET /trees/1/edit
  def edit
  end

  # POST /trees or /trees.json
  def create
    @tree = current_user.build_tree(tree_params)

    respond_to do |format|
      if @tree.save
        format.html { redirect_to @tree, notice: "Tree was successfully created." }
        format.json { render :show, status: :created, location: @tree }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trees/1 or /trees/1.json
  def update
    respond_to do |format|
      if @tree.update(tree_params)
        format.html { redirect_to @tree, notice: "Tree was successfully updated." }
        format.json { render :show, status: :ok, location: @tree }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trees/1 or /trees/1.json
  def destroy
    @tree.destroy!

    respond_to do |format|
      format.html { redirect_to trees_path, status: :see_other, notice: "Tree was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tree
      # friendly_id used to make the link more human-readable
      @tree = Tree.friendly.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def tree_params
      params.require(:tree).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/trees_helper.rb
module TreesHelper
end

app/views/home/index.html.erb
<% stylesheet_link_tag("home")%>
<div class="hero">
  <div class="hero-content">
    <h1 class="header">Your Links,</h1>
    <h1 class="header">All in One Place!</h1>
    <p class="subheader">Easily create a personalized link tree to share your social media, website, and more in a click.
    </p>
    <%if current_user %>
      <button class="home-button">
        <%= link_to("View My Tree", current_user.tree || new_tree_path, class:"hero-link")%>
      </button>
    <% else %>
      <button class="home-button">
        <%= link_to("Get Started", new_user_session_path, class:"hero-link")%>
      </button>
    <%end %>
  </div>
  <%= image_tag("tree.jpg", class:"hero-image") %>
</div>

app/views/layouts/_navbar.html.erb
<% stylesheet_link_tag("navbar")%>
<div class="navbar">
  <div class="navbar-logo">
    <%= link_to image_tag("tree.jpg", class: "navbar-logo"), home_index_path%>
  </div>
  <%if user_signed_in? %>
    <div class="navbar-button">
      <%= link_to "Log out", destroy_user_session_path, class: "nav-link" %>
    </div>
  <%else %>
    <div class="navbar-button">
      <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
    </div>
  <%end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Linktreeclone" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar"%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_with(model: link) do |form| %>
  <% if link.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
        <% link.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :website_title, style: "display: block" %>
    <%= form.text_field :website_title %>
  </div>

  <div>
    <%= form.label :logo_url, style: "display: block" %>
    <%= form.text_field :logo_url %>
  </div>

  <div>
    <%= form.label :website_url, style: "display: block" %>
    <%= form.text_field :website_url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/links/_link.html.erb
<% stylesheet_link_tag("link") %>
<%= link_to link.website_url, class:"link-url" do%>
  <div class="link-container" id="<%= dom_id link %>">
    <%= image_tag(link.logo_url, alt: link.website_title, class: "link-logo") %>
    <div class="link-title-container">
      <p class="link-title">
        <%= link.website_title %>
      </p>
    </div>
  </div>
<% end %>

app/views/links/edit.html.erb
<% content_for :title, "Editing link" %>

<h1>Editing link</h1>

<%= render "form", link: @link %>

<br>

<div>
  <%= link_to "Show this link", @link %> |
  <%= link_to "Back to links", links_path %>
</div>

app/views/links/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Links" %>

<h1>Links</h1>

<div id="links">
  <% @links.each do |link| %>
    <%= render link %>
    <p>
      <%= link_to "Show this link", link %>
    </p>
  <% end %>
</div>

<%= link_to "New link", new_link_path %>

app/views/links/new.html.erb
<% content_for :title, "New link" %>

<h1>New link</h1>

<%= render "form", link: @link %>

<br>

<div>
  <%= link_to "Back to links", links_path %>
</div>

app/views/links/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @link %>

<div>
  <%= link_to "Edit this link", edit_link_path(@link) %> |
  <%= link_to "Back to links", links_path %>

  <%= button_to "Destroy this link", @link, method: :delete %>
</div>

app/views/trees/_form.html.erb
<%= form_with(model: tree) do |form| %>
  <% if tree.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tree.errors.count, "error") %> prohibited this tree from being saved:</h2>
      <ul>
        <% tree.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <%= button_to("Add link", add_link_path, remote: true, method: :get, class: "btn") %>
  <div id="links-container">
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/trees/_tree.html.erb
<% stylesheet_link_tag("show_tree") %>
<div class="tree-container">
  <div id="tree" id="<%= dom_id tree %>">
    <div class="tree-header">
      <img class="profile-pic" src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.kfZ_ddXoQdV76fI2c0eAwQAAAA%26pid%3DApi&f=1&ipt=02fb4241973f970ca26c42b6810b4537a27ece7b787c672c210ade68b37e5e37&ipo=images" alt="Profile Picture">
      <h2 class="tree-name"><%= tree.name %></h2>
    </div>
    <div id="links">
      <% @tree.link.each do |link| %>
        <%= render link %>
      <% end %>
    </div>
  </div>
  <div id="action-container">
    <%= image_tag("edit.svg", class: "action-button")%>
    <%= image_tag("delete.svg", class: "action-button")%>
    <%= image_tag("copy.svg", class: "action-button")%>
  </div>
</div>

app/views/trees/edit.html.erb
<% content_for :title, "Editing tree" %>

<h1>Editing tree</h1>

<%= render "form", tree: @tree %>

<br>

<div>
  <%= link_to "Show this tree", @tree %> |
  <%= link_to "Back to trees", trees_path %>
</div>

app/views/trees/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Trees" %>

<h1>Trees</h1>

<%# TODO: Remove this page since it doesn't really make sense to display all trees %>
<div id="trees">
  <% @trees.each do |tree| %>
    <%= render tree %>
    <p>
      <%= link_to "Show this tree", tree %>
    </p>
  <% end %>
</div>

<%= link_to "New tree", new_tree_path %>

app/views/trees/new.html.erb
<% content_for :title, "New tree" %>
<div class="container">
  <div class="new-tree-container">
    <h1>New tree</h1>
    <%= render "form", tree: @tree %>
  </div>
</div>

app/views/trees/show.html.erb
<p style="color: green"><%= notice %></p>

<%# TODO:  If user signed in, then disallow another user to edit the user %>
<%= render @tree %>

<% if user_signed_in? %>
  <div>
    <%= link_to "Edit this tree", edit_tree_path(@tree) %> |
    <%= link_to "Back to trees", trees_path %>
    <%= button_to "Destroy this tree", @tree, method: :delete %>
  </div>  
<%end %>